<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pers.zkx</groupId>
        <artifactId>algo-java</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>algo-serializable</artifactId>
    <properties>
        <thrift.version>0.14.2</thrift.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>pers.zkx</groupId>
            <artifactId>algo-api</artifactId>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <!-- 可选：Maven 插件自动生成 Thrift Java 代码 -->
            <plugin>
                <groupId>org.apache.thrift.tools</groupId>
                <artifactId>maven-thrift-plugin</artifactId>
                <version>0.1.11</version>
                <executions>
                    <execution>
                        <id>thrift-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <generator>java</generator>
                    <!-- 可选：指定 thrift 可执行文件路径 -->
                    <!-- <thriftExecutable>/usr/local/bin/thrift</thriftExecutable> -->
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
