<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pers.zkx</groupId>
        <artifactId>algo-java</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>algo-api</artifactId>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <thrift.executable>thrift</thrift.executable>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.thrift</groupId>
            <artifactId>libthrift</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.thrift</groupId>
                <artifactId>thrift-maven-plugin</artifactId>
                <version>0.21.0</version>
                <executions>
                    <execution>
                        <id>thrift-sources</id>
                        <phase>generate-sources</phase>
                    </execution>
                </executions>
                <configuration>
                    <generator>java</generator>
                    <thriftExecutable>${thrift.executable}</thriftExecutable>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>thrift-windows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <thrift.executable>D:\Environment\thrift\thrift.exe</thrift.executable>
            </properties>
        </profile>

        <profile>
            <id>thrift-linux</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <properties>
                <thrift.executable>/usr/local/bin/thrift</thrift.executable>
            </properties>
        </profile>

        <profile>
            <id>thrift-macos</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <thrift.executable>/opt/homebrew/bin/thrift</thrift.executable>
            </properties>
        </profile>
    </profiles>
</project>
